package com.aitrader.hammer1430;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.media.*;
import android.os.*;
import android.speech.tts.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.json.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.*;
import org.robolectric.android.controller.*;
import static org.junit.Assert.*;

@RunWith(RobolectricTestRunner.class)
@Config(sdk=35,application=Application.class,qualifiers="w390dp-h844dp-xxhdpi",shadows={HoldingLiveTest.Feed.class,HoldingLiveTest.Speech.class,HoldingLiveTest.Focus.class})
@GraphicsMode(GraphicsMode.Mode.NATIVE)
public class HoldingLiveTest {
    static long now=MinuteBehavior.epoch("2026-01-05 09:40"),elapsed=1000;
    static volatile int quoteCalls,fullCalls,recentCalls;static boolean failFive,extend,newFrame;static double gain=2.2;
    @Implements(value=TencentClient.class,isInAndroidSdk=false)
    public static class Feed {
        @Implementation protected static List<TencentClient.Quote> quotes(List<String> codes){quoteCalls++;List<TencentClient.Quote> out=new ArrayList<>();for(String code:codes)out.add(new TencentClient.Quote(code,"测试持仓",new DailyBar("2026-01-05",10,11,9.9,10*(1+gain/100),100),10,now/1000));return out;}
        @Implementation protected static List<DailyBar> minutes(String code,int interval)throws Exception{fullCalls++;if(failFive)throw new IOException("断网");return five();}
        @Implementation protected static List<DailyBar> recentFiveMinutes(String code)throws Exception{recentCalls++;if(failFive)throw new IOException("断网");List<DailyBar> all=five();return all.subList(960,all.size());}
    }
    @Implements(TextToSpeech.class)
    public static class Speech {
        static List<String> spoken=new ArrayList<>();static int engines,shutdowns,language=0,languageCalls;static UtteranceProgressListener progress;static boolean initialize=true;
        @Implementation protected void __constructor__(Context c,TextToSpeech.OnInitListener listener){engines++;if(initialize)new Handler(Looper.getMainLooper()).post(()->listener.onInit(TextToSpeech.SUCCESS));}
        @Implementation protected int initTts(){return TextToSpeech.SUCCESS;}
        @Implementation protected int setLanguage(Locale l){languageCalls++;return language;}
        @Implementation protected Set<Voice> getVoices(){return Collections.emptySet();}
        @Implementation protected int setSpeechRate(float rate){return 0;}
        @Implementation protected int setAudioAttributes(AudioAttributes a){return 0;}
        @Implementation protected int setOnUtteranceProgressListener(UtteranceProgressListener l){progress=l;return 0;}
        @Implementation protected boolean isSpeaking(){return false;}
        @Implementation protected int speak(CharSequence text,int mode,Bundle b,String id){spoken.add(text.toString());if(progress!=null)progress.onDone(id);return TextToSpeech.SUCCESS;}
        @Implementation protected int stop(){return 0;}
        @Implementation protected void shutdown(){shutdowns++;}
    }
    @Implements(AudioManager.class)
    public static class Focus {
        static int releases;static List<AudioFocusRequest> requests=new ArrayList<>();
        @Implementation protected int requestAudioFocus(AudioFocusRequest r){requests.add(r);return AudioManager.AUDIOFOCUS_REQUEST_GRANTED;}
        @Implementation protected int abandonAudioFocusRequest(AudioFocusRequest r){releases++;return 0;}
    }
    public static class TestService extends HoldingLiveService {
        @Override protected long wallNow(){return now;}
        @Override protected long elapsedNow(){return elapsed;}
    }
    static List<DailyBar> five(){List<DailyBar> out=new ArrayList<>();String previous="";for(DailyBar b:TradingFeaturesTest.behaviorBars().subList(0,320)){String day=b.date.substring(0,10);if(day.equals(previous))continue;previous=day;for(int i=0;i<48;i++){LocalTime time=i<24?LocalTime.of(9,35).plusMinutes(i*5):LocalTime.of(13,5).plusMinutes((i-24)*5);out.add(new DailyBar(day+" "+time,10,10.02,9.98,10,100));}}
        out.add(new DailyBar("2026-01-05 09:35",10.5,10.6,10.1,10.2,300));if(extend)out.add(new DailyBar("2026-01-05 09:40",10.2,10.3,10.0,10.1,300));else out.add(new DailyBar("2026-01-05 09:40",10.2,10.3,10.1,10.2,100));
        out.add(new DailyBar("2026-01-05 09:45",10.8,11.0,10.7,10.8,100));if(newFrame){out.add(new DailyBar("2026-01-05 09:50",11.2,11.4,10.8,11,400));}return out;
    }
    private Application app(){return RuntimeEnvironment.getApplication();}
    @Before public void reset()throws Exception{now=MinuteBehavior.epoch("2026-01-05 09:40");elapsed=1000;gain=2.2;quoteCalls=fullCalls=recentCalls=0;failFive=extend=newFrame=false;Speech.spoken.clear();Speech.engines=Speech.shutdowns=Speech.languageCalls=0;Speech.language=0;Speech.initialize=true;Speech.progress=null;Focus.releases=0;Focus.requests.clear();
        for(String p:new String[]{"holdings","watchlist","holding_live","holding_five","personal_signals","scan","minute15_cache"})app().getSharedPreferences(p,0).edit().clear().commit();for(String code:new String[]{"000001","600519"}){new File(app().getFilesDir(),"minute_history_v2/5/"+code+".json").delete();new File(app().getFilesDir(),"minute_history_v2/15/"+code+".json").delete();}HoldingsStore.add(app(),"000001","平安银行","银行");HoldingsStore.stop(app(),"000001",10.3);Shadows.shadowOf(app()).grantPermissions(android.Manifest.permission.POST_NOTIFICATIONS);HoldingLive.publish(app(),Feed.quotes(Collections.singletonList("000001")),now);quoteCalls=0;
    }
    @Test public void numberOnlySpeechAndWindowHaveExplicitBoundaries(){assertEquals("2.2",HoldingLive.spoken(2.2));assertEquals("负2.2",HoldingLive.spoken(-2.2));assertEquals("0",HoldingLive.spoken(-0.004));assertEquals("12.35",HoldingLive.spoken(12.345));assertNull(HoldingLive.spoken(Double.NaN));assertTrue(HoldingLive.duration(30));assertTrue(HoldingLive.duration(60));assertTrue(HoldingLive.duration(120));assertFalse(HoldingLive.duration(2));assertFalse(HoldingLive.window(MinuteBehavior.epoch("2026-01-05 08:59")));assertTrue(HoldingLive.window(MinuteBehavior.epoch("2026-01-05 09:00")));assertTrue(HoldingLive.window(MinuteBehavior.epoch("2026-01-05 14:59")));assertFalse(HoldingLive.window(MinuteBehavior.epoch("2026-01-05 15:00")));assertFalse(HoldingLive.window(MinuteBehavior.epoch("2026-01-04 10:00")));assertEquals(3000,HoldingLive.QUOTE_MS);assertEquals(5000,HoldingLive.SPEECH_MS);}
    @Test public void stalePreviousDayAndFutureQuotesNeverSpeak()throws Exception{JSONObject q=HoldingLive.quotes(app()).getJSONObject("000001");assertTrue(HoldingLive.fresh(q,now));assertFalse(HoldingLive.fresh(q,now+45_001));q.put("quote_time","2026-01-02 15:00:00");assertFalse(HoldingLive.fresh(q,now));q.put("quote_time","2026-01-05 09:40:00").put("quote_at",now+5001);assertFalse(HoldingLive.fresh(q,now));}
    @Test public void fastQuotesCannotOverwriteNewerQuotesOrOtherModuleData()throws Exception{app().getSharedPreferences("scan",0).edit().putString("favorite_quote_payload","{\"600519\":{\"latest_price\":100}}").commit();TencentClient.Quote old=new TencentClient.Quote("000001","旧报价",new DailyBar("2026-01-05",10,11,9,9.8,100),10,(now-10_000)/1000);HoldingLive.publish(app(),Collections.singletonList(old),now);assertEquals(10.22,HoldingLive.quotes(app()).getJSONObject("000001").getDouble("latest_price"),1e-8);assertEquals(100,new JSONObject(app().getSharedPreferences("scan",0).getString("favorite_quote_payload","{}")).getJSONObject("600519").getDouble("latest_price"),0);HoldingsStore.remove(app(),"000001");HoldingLive.publish(app(),Collections.singletonList(old),now);assertEquals(0,HoldingLive.quotes(app()).length());}
    @Test public void fiveMinuteAlertIsSolidEndedDeduplicatedAndIndependentOfFifteen()throws Exception{HoldingFiveRepository repo=new HoldingFiveRepository();repo.scan(app(),now);assertEquals(1,fullCalls);assertTrue(HoldingFiveStore.unread(app(),"000001"));assertFalse(PersonalSignalStore.unread(app(),"000001"));NotificationManager nm=(NotificationManager)app().getSystemService(Context.NOTIFICATION_SERVICE);Notification n=Shadows.shadowOf(nm).getNotification(2_050_001);assertNotNull(n);assertEquals(android.provider.Settings.System.DEFAULT_NOTIFICATION_URI,nm.getNotificationChannel(HoldingRiskNotifier.FIVE_CHANNEL).getSound());Intent route=Shadows.shadowOf(n.contentIntent).getSavedIntent();assertEquals(5,route.getIntExtra(StockChartActivity.EXTRA_PERIOD,0));assertEquals("2026-01-05 09:35",route.getStringExtra(StockChartActivity.EXTRA_FOCUS));assertEquals(0,Speech.engines);
        nm.cancel(2_050_001);repo.scan(app(),now);assertEquals(1,fullCalls);assertNull(Shadows.shadowOf(nm).getNotification(2_050_001));extend=true;now=MinuteBehavior.epoch("2026-01-05 09:45");repo.scan(app(),now);assertNull(Shadows.shadowOf(nm).getNotification(2_050_001));assertEquals(1,recentCalls);assertEquals("2026-01-05 09:40",HoldingFiveStore.reductions(app(),"000001").getJSONObject(0).getString("end_time"));HoldingFiveStore.acknowledge(app(),"000001");assertFalse(HoldingFiveStore.unread(app(),"000001"));newFrame=true;now=MinuteBehavior.epoch("2026-01-05 09:50");repo.scan(app(),now);assertNotNull(Shadows.shadowOf(nm).getNotification(2_050_001));assertTrue(HoldingFiveStore.unread(app(),"000001"));assertEquals(2,HoldingFiveStore.reductions(app(),"000001").length());
    }
    @Test public void failedFiveRefreshRetainsAlertsAndNoHistoricalHolidayReplay()throws Exception{HoldingFiveRepository r=new HoldingFiveRepository();r.scan(app(),now);NotificationManager nm=(NotificationManager)app().getSystemService(Context.NOTIFICATION_SERVICE);nm.cancel(2_050_001);failFive=true;now=MinuteBehavior.epoch("2026-01-05 09:45");r.scan(app(),now);assertTrue(HoldingFiveStore.records(app()).getJSONObject("000001").getBoolean("stale"));assertEquals(1,HoldingFiveStore.reductions(app(),"000001").length());assertNull(Shadows.shadowOf(nm).getNotification(2_050_001));int calls=fullCalls+recentCalls;now=MinuteBehavior.epoch("2026-01-06 09:45");r.scan(app(),now);assertEquals(calls,fullCalls+recentCalls);assertNull(Shadows.shadowOf(nm).getNotification(2_050_001));}
    @Test public void unfinishedAndContainedFiveFramesDoNotAlert()throws Exception{JSONObject held=HoldingsStore.find(app(),"000001");assertEquals(1,HoldingFiveStore.evaluate(held,five(),"2026-01-05",now).getJSONArray("reductions").length());try{HoldingFiveStore.evaluate(held,five(),"2026-01-05",MinuteBehavior.epoch("2026-01-05 09:34"));fail();}catch(Exception expected){}List<DailyBar> bars=five();bars.set(960,new DailyBar("2026-01-05 09:35",10,12,9,11,300));bars.set(961,new DailyBar("2026-01-05 09:40",11,11.2,10.8,11,100));bars.add(new DailyBar("2026-01-05 09:45",11,11.5,10.5,10.8,300));assertEquals(0,HoldingFiveStore.evaluate(held,bars,"2026-01-05",MinuteBehavior.epoch("2026-01-05 09:45")).getJSONArray("reductions").length());}
    private ServiceController<TestService> service(){return Robolectric.buildService(TestService.class).create();}
    private void waitQuotes(int count)throws Exception{long end=System.nanoTime()+3_000_000_000L;while((quoteCalls<count||Math.abs(HoldingLive.quotes(app()).optJSONObject("000001").optDouble("change")-gain)>1e-7)&&System.nanoTime()<end){Thread.sleep(10);Shadows.shadowOf(Looper.getMainLooper()).idle();}assertTrue(quoteCalls>=count);}
    @Test public void manualSpeechUsesFiveSecondLatestGainAndThreeSecondQuotesThenStops()throws Exception{ServiceController<TestService> controller=service();TestService s=controller.get();try{s.onStartCommand(new Intent().setAction(HoldingLiveService.SPEAK).putExtra("code","000001").putExtra("minutes",30),0,1);Shadows.shadowOf(Looper.getMainLooper()).idle();waitQuotes(1);assertEquals(Collections.singletonList("2.2"),Speech.spoken);assertTrue(HoldingLive.prefs(app()).getBoolean("speech_active",false));gain=-1.5;now+=3000;elapsed+=3000;Shadows.shadowOf(Looper.getMainLooper()).idleFor(Duration.ofSeconds(3));waitQuotes(2);assertEquals(1,Speech.spoken.size());now+=2000;elapsed+=2000;Shadows.shadowOf(Looper.getMainLooper()).idleFor(Duration.ofSeconds(2));assertEquals(Arrays.asList("2.2","负1.5"),Speech.spoken);assertTrue(Focus.releases>=2);elapsed+=30*60_000L;now+=5000;Shadows.shadowOf(Looper.getMainLooper()).idleFor(Duration.ofSeconds(5));assertFalse(HoldingLive.prefs(app()).getBoolean("speech_active",true));assertEquals(2,Speech.spoken.size());assertEquals(1,Speech.shutdowns);}finally{controller.destroy();}}
    @Test public void switchingSelectedStockAndRemovingItStopsOldSession()throws Exception{HoldingsStore.add(app(),"600519","贵州茅台","白酒");HoldingLive.publish(app(),Feed.quotes(Collections.singletonList("600519")),now);ServiceController<TestService> ctl=service();TestService s=ctl.get();try{s.onStartCommand(new Intent().setAction(HoldingLiveService.SPEAK).putExtra("code","000001").putExtra("minutes",60),0,1);Shadows.shadowOf(Looper.getMainLooper()).idle();s.onStartCommand(new Intent().setAction(HoldingLiveService.SPEAK).putExtra("code","600519").putExtra("minutes",120),0,2);Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals("600519",HoldingLive.prefs(app()).getString("speech_code",""));assertEquals(120,HoldingLive.prefs(app()).getInt("speech_minutes",0));assertEquals(1,Speech.shutdowns);AudioManager.OnAudioFocusChangeListener oldFocus=org.robolectric.util.ReflectionHelpers.callInstanceMethod(Focus.requests.get(0),"getOnAudioFocusChangeListener");oldFocus.onAudioFocusChange(AudioManager.AUDIOFOCUS_LOSS);Shadows.shadowOf(Looper.getMainLooper()).idle();assertTrue("Delayed focus loss from old stock must not stop newly selected stock",HoldingLive.prefs(app()).getBoolean("speech_active",false));HoldingsStore.remove(app(),"600519");Shadows.shadowOf(Looper.getMainLooper()).idle();assertFalse(HoldingLive.prefs(app()).getBoolean("speech_active",true));assertEquals(2,Speech.shutdowns);assertFalse(Speech.spoken.stream().anyMatch(t->t.contains("银行")||t.contains("茅台")||t.contains("%")));}finally{ctl.destroy();}}
    @Test public void voiceFailureAndClosingStopWithoutSpeakingStatusText()throws Exception{ServiceController<TestService> ctl=service();TestService s=ctl.get();try{Speech.language=TextToSpeech.LANG_NOT_SUPPORTED;s.onStartCommand(new Intent().setAction(HoldingLiveService.SPEAK).putExtra("code","000001").putExtra("minutes",30),0,1);Shadows.shadowOf(Looper.getMainLooper()).idle();assertTrue(Speech.spoken.isEmpty());assertFalse(HoldingLive.prefs(app()).getBoolean("speech_active",true));assertTrue(HoldingLive.prefs(app()).getString("speech_status","").contains("中文语音"));Speech.language=0;s.onStartCommand(new Intent().setAction(HoldingLiveService.SPEAK).putExtra("code","000001").putExtra("minutes",30),0,2);Shadows.shadowOf(Looper.getMainLooper()).idle();int spoken=Speech.spoken.size();now=MinuteBehavior.epoch("2026-01-05 15:00");elapsed+=5000;Shadows.shadowOf(Looper.getMainLooper()).idleFor(Duration.ofSeconds(5));assertFalse(HoldingLive.prefs(app()).getBoolean("speech_active",true));assertEquals(spoken,Speech.spoken.size());s.onTimeout(1,android.content.pm.ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC);assertTrue(HoldingLive.prefs(app()).getString("tracking_error","").contains("系统"));}finally{ctl.destroy();}}
    @Test public void uninitializedEngineStillEndsAtDeadlineAndStopButtonIsSilent()throws Exception{ServiceController<TestService> ctl=service();TestService s=ctl.get();try{Speech.initialize=false;s.onStartCommand(new Intent().setAction(HoldingLiveService.SPEAK).putExtra("code","000001").putExtra("minutes",30),0,1);Shadows.shadowOf(Looper.getMainLooper()).idle();assertTrue(HoldingLive.prefs(app()).getBoolean("speech_active",false));elapsed+=30*60_000L;now+=5000;Shadows.shadowOf(Looper.getMainLooper()).idleFor(Duration.ofSeconds(5));assertFalse(HoldingLive.prefs(app()).getBoolean("speech_active",true));assertTrue(Speech.spoken.isEmpty());assertEquals(1,Speech.shutdowns);Speech.initialize=true;s.onStartCommand(new Intent().setAction(HoldingLiveService.SPEAK).putExtra("code","000001").putExtra("minutes",60),0,2);Shadows.shadowOf(Looper.getMainLooper()).idle();int count=Speech.spoken.size();s.onStartCommand(new Intent().setAction(HoldingLiveService.STOP_SPEECH),0,3);Shadows.shadowOf(Looper.getMainLooper()).idleFor(Duration.ofSeconds(10));assertEquals(count,Speech.spoken.size());assertFalse(HoldingLive.prefs(app()).getBoolean("speech_active",true));assertEquals(2,Speech.shutdowns);}finally{ctl.destroy();}}
    private ScrollView findScroll(View view){if(view instanceof ScrollView)return (ScrollView)view;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++){ScrollView found=findScroll(((ViewGroup)view).getChildAt(i));if(found!=null)return found;}return null;}
    private View root(Activity a){return ((ViewGroup)a.findViewById(android.R.id.content)).getChildAt(0);}
    private void capture(Activity a,String file,int width,int height)throws Exception{View v=root(a);int w=Ui.dp(a,width),h=Ui.dp(a,height);for(int i=0;i<2;i++){v.forceLayout();v.measure(View.MeasureSpec.makeMeasureSpec(w,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(h,View.MeasureSpec.EXACTLY));v.layout(0,0,w,h);}Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));try(FileOutputStream o=new FileOutputStream(new File(System.getProperty("aitrader.ui.outputs"),file))){b.compress(Bitmap.CompressFormat.PNG,100,o);}b.recycle();}
    @Test public void holdingsUiKeepsRowsAndScrollWhenLiveQuotesArrive()throws Exception{HoldingFiveRepository repo=new HoldingFiveRepository();repo.scan(app(),now);app().getSharedPreferences("scan",0).edit().putString("favorite_quote_payload","{\"000001\":{\"latest_price\":10.22,\"return_30d_pct\":12.0,\"return_end\":\"2026-01-05\",\"quote_time\":\"2026-01-05 09:40:00\"}}").commit();ActivityController<MainActivity> ctl=Robolectric.buildActivity(MainActivity.class,new Intent().putExtra("module",5)).create().start().resume().visible();try{MainActivity a=ctl.get();View r=root(a);View risk=r.findViewWithTag("holding-five-risk:000001");if(risk==null){String industry=new IndustryCatalog(app()).industry("000001");View body=r.findViewWithTag("industry-body:5:"+industry);((View)((ViewGroup)body.getParent()).getChildAt(0)).performClick();}assertNotNull(r.findViewWithTag("holding-five-risk:000001"));View before=r.findViewWithTag("personal-stock:000001");TextView price=r.findViewWithTag("holding-price:000001");assertEquals("¥10.22",price.getText().toString());capture(a,"apk-v1.33-holdings.png",390,844);gain=3.3;now+=3000;HoldingLive.publish(app(),Feed.quotes(Collections.singletonList("000001")),now);Shadows.shadowOf(Looper.getMainLooper()).idle();assertSame(before,r.findViewWithTag("personal-stock:000001"));assertEquals("¥10.33",price.getText().toString());assertEquals("日涨幅 +3.30%",((TextView)r.findViewWithTag("holding-day-change:000001")).getText().toString());a.getResources().getConfiguration().fontScale=1.3f;capture(a,"apk-v1.33-holdings-small.png",320,720);ScrollView scroll=(ScrollView)r.findViewWithTag("main-scroll");if(scroll==null)scroll=findScroll(r);assertNotNull(scroll);scroll.scrollTo(0,Ui.dp(a,260));capture(a,"apk-v1.33-holdings-small-scrolled.png",320,720);Rect visible=new Rect();assertTrue(r.findViewWithTag("holding-speech:000001").getGlobalVisibleRect(visible));assertTrue(((TextView)r.findViewWithTag("holding-day-change:000001")).getLineCount()<=1);int scrollY=scroll.getScrollY();View same=r.findViewWithTag("personal-stock:000001");gain=4.4;now+=3000;HoldingLive.publish(app(),Feed.quotes(Collections.singletonList("000001")),now);Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals(scrollY,scroll.getScrollY());assertSame(same,r.findViewWithTag("personal-stock:000001"));r.findViewWithTag("holding-speech:000001").performClick();AlertDialog dialog=org.robolectric.shadows.ShadowAlertDialog.getLatestAlertDialog();assertEquals(3,dialog.getListView().getCount());assertEquals("2小时",dialog.getListView().getAdapter().getItem(2));dialog.dismiss();r.findViewWithTag("holding-five-risk:000001").performClick();Intent route=Shadows.shadowOf(a).getNextStartedActivity();assertEquals(5,route.getIntExtra(StockChartActivity.EXTRA_PERIOD,0));assertFalse(HoldingFiveStore.unread(app(),"000001"));}finally{ctl.pause().stop().destroy();}}
}
