package com.aitrader.hammer1430;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.time.*;
import java.util.*;
import org.json.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.*;
import org.robolectric.android.controller.ActivityController;
import org.robolectric.shadows.ShadowAlertDialog;
import static org.junit.Assert.*;

@RunWith(RobolectricTestRunner.class)
@Config(sdk=35,application=Application.class,qualifiers="w390dp-h844dp-xxhdpi",shadows=TradingFeaturesTest.FakeTencent.class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
public class NotesAndReviewTest {
    private Context app;
    @Before public void reset()throws Exception{app=RuntimeEnvironment.getApplication();for(String prefs:new String[]{"holdings","watchlist","notes_v1","scan","personal_signals"})app.getSharedPreferences(prefs,0).edit().clear().commit();JSONObject snapshot=WatchlistStore.bundledSnapshot(app);app.getSharedPreferences("watchlist",0).edit().putBoolean("imported:"+snapshot.getString("id"),true).commit();TradingFeaturesTest.failMinutes=false;TradingFeaturesTest.entered=null;TradingFeaturesTest.release=null;}
    private AlertDialog lastDialog(){Shadows.shadowOf(Looper.getMainLooper()).idle();return ShadowAlertDialog.getLatestAlertDialog();}
    private View root(Activity a){return ((ViewGroup)a.findViewById(android.R.id.content)).getChildAt(0);}
    private View named(View v,String name){if(v instanceof TextView&&name.contentEquals(((TextView)v).getText()))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View found=named(((ViewGroup)v).getChildAt(i),name);if(found!=null)return found;}return null;}
    private View description(View v,String name){if(name.contentEquals(v.getContentDescription()==null?"":v.getContentDescription()))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View found=description(((ViewGroup)v).getChildAt(i),name);if(found!=null)return found;}return null;}
    private EditText input(View v){if(v instanceof EditText)return (EditText)v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){EditText found=input(((ViewGroup)v).getChildAt(i));if(found!=null)return found;}return null;}
    private void capture(Activity a,String name,int width,int height)throws Exception{capture(a,root(a),name,width,height);}
    private void capture(Activity a,View v,String name,int width,int height)throws Exception{int w=Ui.dp(a,width),h=Ui.dp(a,height);for(int i=0;i<2;i++){v.forceLayout();v.measure(View.MeasureSpec.makeMeasureSpec(w,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(h,View.MeasureSpec.EXACTLY));v.layout(0,0,w,h);}if(name.contains("extension")){View ratio=v.findViewWithTag("signal-ratio:600519");ScrollView scroll=(ScrollView)((ViewGroup)((ViewGroup)root(a)).getChildAt(1)).getChildAt(0);int[] rp=new int[2],sp=new int[2];ratio.getLocationOnScreen(rp);scroll.getLocationOnScreen(sp);scroll.scrollBy(0,rp[1]-sp[1]-Ui.dp(a,100));assertTrue(ratio.getGlobalVisibleRect(new Rect()));}Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));try(FileOutputStream out=new FileOutputStream(new File(System.getProperty("aitrader.ui.outputs"),name))){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}
    @Test public void datedNotesAppendAndStaySeparateAfterGroupRemoval()throws Exception{
        String key=NotesStore.stock("600519");long day1=Instant.parse("2026-09-01T16:00:00Z").toEpochMilli(),day2=Instant.parse("2026-09-02T16:00:00Z").toEpochMilli();NotesStore.append(app,key,"第一天的量价笔记",day1);NotesStore.append(app,key,"第二天继续观察",day2);NotesStore.append(app,key,"同日补充",day2);
        JSONArray notes=NotesStore.notes(app,key);assertEquals(3,notes.length());assertEquals("2026/09/02：第一天的量价笔记",NotesStore.line(notes.getJSONObject(0)));assertEquals("2026/09/03：第二天继续观察",NotesStore.line(notes.getJSONObject(1)));assertNotEquals(notes.getJSONObject(1).getString("id"),notes.getJSONObject(2).getString("id"));
        NotesStore.append(app,NotesStore.board("房地产",false),"行业观察",day1);NotesStore.append(app,NotesStore.board("房地产",true),"概念观察",day2);assertEquals("行业观察",NotesStore.notes(app,NotesStore.board("房地产",false)).getJSONObject(0).getString("body"));assertEquals("概念观察",NotesStore.notes(app,NotesStore.board("房地产",true)).getJSONObject(0).getString("body"));
        HoldingsStore.add(app,"600519","贵州茅台","白酒");HoldingsStore.remove(app,"600519");WatchlistStore.add(app,"600519","贵州茅台","白酒");WatchlistStore.remove(app,"600519");assertEquals(3,NotesStore.notes(app,key).length());try{NotesStore.append(app,key,"  ");fail();}catch(IOException expected){}assertEquals(3,NotesStore.notes(app,key).length());
    }
    @Test public void optionalLogicPairsOnlyWithinTheSameClosedHoldingEpisode()throws Exception{
        HoldingsStore.add(app,"600519","贵州茅台","白酒","第一段买入理由");String first=HoldingsStore.find(app,"600519").getString("trade_cycle_id");HoldingsStore.stop(app,"600519",9.5);HoldingsStore.add(app,"600519","贵州茅台","白酒");assertEquals(first,HoldingsStore.find(app,"600519").getString("trade_cycle_id"));assertEquals(9.5,HoldingsStore.find(app,"600519").getDouble("stop_price"),0);TradeJournal.addLogic(app,first,"sell_notes","第一段卖出理由");assertTrue(TradeJournal.reviews(app).isEmpty());HoldingsStore.remove(app,"600519");assertNull(HoldingsStore.find(app,"600519"));assertEquals(1,TradeJournal.reviews(app).size());
        HoldingsStore.add(app,"600519","贵州茅台","白酒");String second=HoldingsStore.find(app,"600519").getString("trade_cycle_id");assertNotEquals(first,second);assertFalse(HoldingsStore.find(app,"600519").has("stop_price"));HoldingsStore.remove(app,"600519","第二段卖出理由");assertEquals(1,TradeJournal.reviews(app).size());TradeJournal.addLogic(app,second,"buy_notes","补填第二段买入理由");assertEquals(2,TradeJournal.reviews(app).size());assertEquals("第一段买入理由",TradeJournal.find(TradeJournal.cycles(app),first).getJSONArray("buy_notes").getJSONObject(0).getString("body"));
        HoldingsStore.add(app,"600519","贵州茅台","白酒","第三段只有买入");HoldingsStore.remove(app,"600519");assertEquals(2,TradeJournal.reviews(app).size());assertEquals(3,TradeJournal.cycles(app).length());
        app.getSharedPreferences("holdings",0).edit().putString("stocks","[{\"code\":\"000001\",\"name\":\"旧版持仓\",\"industry\":\"银行\",\"stop_price\":8.5}]").commit();String legacy=TradeJournal.current(app,"000001");TradeJournal.addLogic(app,legacy,"buy_notes","旧持仓补填");assertEquals(8.5,HoldingsStore.find(app,"000001").getDouble("stop_price"),0);HoldingsStore.remove(app,"000001","旧持仓卖出");assertEquals(3,TradeJournal.reviews(app).size());
    }
    @Test public void optionalHoldingDialogsAndReviewModuleSurviveRecreation()throws Exception{
        WatchlistStore.add(app,"600519","贵州茅台","白酒");ActivityController<MainActivity> controller=Robolectric.buildActivity(MainActivity.class,new Intent().putExtra("module",2)).create().start().resume().visible();
        try{MainActivity a=controller.get();root(a).findViewWithTag("notes:stock:600519").performClick();AlertDialog notes=lastDialog();EditText editor=input(notes.getWindow().getDecorView());editor.setText("观察放量后承接");notes.getButton(-1).performClick();editor.setText("继续等待信号");notes.getButton(-1).performClick();assertEquals(2,NotesStore.notes(a,NotesStore.stock("600519")).length());assertNotNull(named(notes.getWindow().getDecorView(),NotesStore.today()+"：观察放量后承接"));capture(a,notes.getWindow().getDecorView(),"apk-v1.30-notes.png",390,680);notes.dismiss();Shadows.shadowOf(Looper.getMainLooper()).idle();
            description(root(a),"贵州茅台加入持仓").performClick();AlertDialog join=lastDialog();join.getButton(-2).performClick();assertNull(HoldingsStore.find(a,"600519"));description(root(a),"贵州茅台加入持仓").performClick();join=lastDialog();input(join.getWindow().getDecorView()).setText("放量突破，回踩确认");join.getButton(-1).performClick();assertNotNull(HoldingsStore.find(a,"600519"));
            HoldingDialogs.remove(a,"600519","贵州茅台",()->{});AlertDialog sell=lastDialog();input(sell.getWindow().getDecorView()).setText("跌破结构止损，离场复盘");sell.getButton(-1).performClick();description(root(a),"交割单复盘").performClick();Shadows.shadowOf(Looper.getMainLooper()).idle();assertNotNull(root(a).findViewWithTag("review-stock:600519"));assertNotNull(named(root(a),NotesStore.today()+"：放量突破，回踩确认"));assertNotNull(named(root(a),NotesStore.today()+"：跌破结构止损，离场复盘"));capture(a,"apk-v1.30-review.png",390,844);RuntimeEnvironment.setFontScale(1.3f);capture(a,"apk-v1.30-review-small.png",320,720);RuntimeEnvironment.setFontScale(1f);
            Bundle saved=new Bundle();controller.pause().stop().saveInstanceState(saved).destroy();controller=Robolectric.buildActivity(MainActivity.class).create(saved).start().resume().visible();a=controller.get();assertNotNull(root(a).findViewWithTag("review-stock:600519"));assertEquals(2,NotesStore.notes(a,NotesStore.stock("600519")).length());
            HoldingDialogs.add(a,"600036","招商银行","银行",()->{});lastDialog().getButton(-1).performClick();HoldingDialogs.remove(a,"600036","招商银行",()->{});lastDialog().getButton(-1).performClick();assertNull(HoldingsStore.find(a,"600036"));assertEquals(1,TradeJournal.reviews(a).size());
        }finally{if(!controller.get().isDestroyed())controller.pause().stop().destroy();RuntimeEnvironment.setFontScale(1f);}
    }
    @Test public void stockAndBothBoardChartTypesExposeTheSamePersistentNotes()throws Exception{
        NotesStore.append(app,NotesStore.stock("600519"),"列表记录");ActivityController<StockChartActivity> stock=Robolectric.buildActivity(StockChartActivity.class,new Intent().putExtra(StockChartActivity.EXTRA_CODE,"600519").putExtra(StockChartActivity.EXTRA_NAME,"贵州茅台")).create().start().resume().visible();try{root(stock.get()).findViewWithTag("notes:stock:600519").performClick();AlertDialog d=lastDialog();assertNotNull(named(d.getWindow().getDecorView(),NotesStore.today()+"：列表记录"));d.dismiss();}finally{stock.pause().stop().destroy();}
        for(boolean concept:new boolean[]{false,true}){ActivityController<BoardChartActivity> board=Robolectric.buildActivity(BoardChartActivity.class,new Intent().putExtra(BoardChartActivity.EXTRA_INDUSTRY,"房地产").putExtra(BoardChartActivity.EXTRA_TYPE,concept?"concept":"industry")).create().start().resume().visible();try{String key=NotesStore.board("房地产",concept);root(board.get()).findViewWithTag("notes:"+key).performClick();AlertDialog d=lastDialog();input(d.getWindow().getDecorView()).setText(concept?"概念笔记":"行业笔记");d.getButton(-1).performClick();d.dismiss();assertEquals(1,NotesStore.notes(app,key).length());}finally{board.pause().stop().destroy();}}
    }
    private List<String> calendar(){return Arrays.asList("2026-09-17","2026-09-18","2026-09-21","2026-09-22","2026-09-23","2026-09-24","2026-09-25","2026-09-28","2026-09-29","2026-09-30");}
    @Test public void personalQuoteRefreshReplacesOldRatioAlongsideLatestPrice()throws Exception{
        WatchlistStore.add(app,"600519","贵州茅台","白酒");NotesStore.append(app,NotesStore.stock("600519"),"行情刷新保留此笔记");app.getSharedPreferences("scan",0).edit().putString("favorite_quote_payload","{\"600519\":{\"latest_price\":999,\"risk_ratio\":{\"available\":true,\"ratio\":999}}}").commit();PersonalQuotes.load(app);JSONObject value=new JSONObject(app.getSharedPreferences("scan",0).getString("favorite_quote_payload","{}")).getJSONObject("600519");assertEquals(10.078,value.getDouble("latest_price"),1e-9);JSONObject ratio=value.getJSONObject("risk_ratio");assertTrue(ratio.toString(),ratio.getBoolean("available"));assertEquals(.278/.122,ratio.getDouble("ratio"),1e-9);assertEquals(value.getString("quote_time"),ratio.getString("quote_time"));assertEquals(1,NotesStore.notes(app,NotesStore.stock("600519")).length());
    }
    private List<DailyBar> daily(){List<DailyBar> out=new ArrayList<>();for(String day:calendar())out.add(new DailyBar(day,11,15,9,12,100));out.add(0,new DailyBar("2026-09-16",11,50,5,12,100));return out;}
    private TencentClient.Quote quote(double price,double high,double low,String time){return new TencentClient.Quote("600519","贵州茅台",new DailyBar("2026-09-30",11,high,low,price,100),11,MinuteBehavior.epoch("2026-09-30 "+time)/1000);}
    @Test public void ratioUsesCurrentPriceTwoDayLowAndExactlyTenMarketSessions()throws Exception{
        List<DailyBar> rows=daily();rows.set(rows.size()-2,new DailyBar("2026-09-29",11,15,8,12,100));JSONObject value=RiskRatio.calculate(rows,calendar(),quote(12,13,10,"14:45"));assertTrue(value.getBoolean("available"));assertEquals(12,value.getDouble("entry"),0);assertEquals(8,value.getDouble("stop"),0);assertEquals(15,value.getDouble("target"),0);assertEquals(4.0/3,value.getDouble("ratio"),1e-9);assertEquals("盘中最新价",value.getString("phase"));
        value=RiskRatio.calculate(rows,calendar(),quote(13,16,7,"15:00"));assertEquals(7,value.getDouble("stop"),0);assertEquals(16,value.getDouble("target"),0);assertEquals(2,value.getDouble("ratio"),0);assertEquals("收盘价",value.getString("phase"));
        assertFalse(RiskRatio.calculate(rows,calendar(),quote(15,15,10,"15:00")).getBoolean("available"));assertEquals(0,RiskRatio.calculate(rows,calendar(),quote(8,15,8,"14:45")).getDouble("ratio"),0);rows.remove(rows.size()-2);assertFalse(RiskRatio.calculate(rows,calendar(),quote(12,13,10,"15:00")).getBoolean("available"));assertFalse(RiskRatio.calculate(daily(),calendar().subList(1,10),quote(12,13,10,"15:00")).getBoolean("available"));
    }
    @Test public void extensionRatioIsBetweenNameAndCodeAndRejectsStaleQuotes()throws Exception{
        WatchlistStore.add(app,"600519","贵州茅台","白酒");JSONObject ratio=RiskRatio.calculate(daily(),calendar(),quote(12,13,10,"15:00"));JSONObject row=new JSONObject().put("code","600519").put("qualifies",true).put("previous_date","2026-09-29").put("previous_bearish",true).put("previous_open",12).put("previous_close",11).put("rule_version",PersonalSignalRule.VERSION).put("risk_ratio",ratio).put("first_attack",new JSONObject().put("start_time","2026-09-30 09:45").put("end_time","2026-09-30 09:45")).put("second_attack",new JSONObject().put("start_time","2026-09-30 10:15").put("end_time","2026-09-30 10:15"));app.getSharedPreferences("personal_signals",0).edit().putString("payload",new JSONObject().put("trade_date","2026-09-30").put("stocks",new JSONObject().put("600519",row)).toString()).commit();app.getSharedPreferences("scan",0).edit().putString("favorite_quote_payload",new JSONObject().put("600519",new JSONObject().put("latest_price",12).put("quote_time",ratio.getString("quote_time")).put("return_30d_pct",10).put("risk_ratio",ratio)).toString()).commit();
        ActivityController<MainActivity> controller=Robolectric.buildActivity(MainActivity.class,new Intent().putExtra("module",6)).create().start().resume().visible();try{MainActivity a=controller.get();LinearLayout identity=(LinearLayout)root(a).findViewWithTag("stock-identity:600519");assertEquals("贵州茅台",((TextView)identity.getChildAt(0)).getText().toString());assertEquals("盈亏比1.00",((TextView)identity.getChildAt(1)).getText().toString());assertEquals("600519",((TextView)identity.getChildAt(2)).getText().toString());capture(a,"apk-v1.30-extension.png",390,844);RuntimeEnvironment.setFontScale(1.3f);capture(a,"apk-v1.30-extension-small.png",320,720);RuntimeEnvironment.setFontScale(1f);identity.getChildAt(1).performClick();AlertDialog d=lastDialog();assertTrue(((TextView)d.findViewById(android.R.id.message)).getText().toString().contains("止损点 9.00"));d.dismiss();
            app.getSharedPreferences("scan",0).edit().putString("favorite_quote_payload",new JSONObject().put("600519",new JSONObject().put("quote_time","2026-09-30 15:01:00").put("risk_ratio",ratio)).toString()).commit();Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals("盈亏比—",((TextView)root(a).findViewWithTag("signal-ratio:600519")).getText().toString());
        }finally{controller.pause().stop().destroy();RuntimeEnvironment.setFontScale(1f);}
    }
}
